# Generated by Django 5.1.4 on 2025-01-09 09:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('7c0d65bd-7cdf-416a-8cc0-159caedbaa30'), editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='Homecarousel/')),
                ('title', models.TextField(blank=True, null=True)),
                ('subtitle', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
