# Generated by Django 5.1.4 on 2025-01-09 09:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('989fee2a-47d3-4d49-a256-75eab82cf2c2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
