# Generated by Django 5.1.4 on 2025-01-09 10:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_carousel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
