# Generated by Django 5.1.4 on 2025-01-11 15:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_carousel_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='Service/')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField()),
            ],
        ),
    ]
