# Generated by Django 5.1.4 on 2025-01-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_ourservice_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='achievements/')),
                ('category', models.CharField(choices=[('recognition', 'Recognition'), ('project', 'Project'), ('material_supply', 'Material Supply')], max_length=100)),
            ],
        ),
    ]
