# Generated by Django 5.1.4 on 2025-01-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_alter_blog_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='team/')),
                ('position', models.CharField(max_length=200)),
                ('other_position', models.CharField(blank=True, max_length=200, null=True)),
                ('board_member', models.BooleanField(default=False)),
            ],
        ),
    ]
