# Generated by Django 5.1.4 on 2025-02-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_team_linkedin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='team',
            name='management_team',
            field=models.BooleanField(default=False),
        ),
    ]
