# Generated by Django 5.1.4 on 2025-04-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_alter_carousel_options_carousel_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='Homecarousel/videos/'),
        ),
    ]
