# Generated by Django 5.1.4 on 2025-04-17 07:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_carousel_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='media'),
        ),
    ]
